### ISSUE TITLE
Publis to the crates.io

### ISSUE THREAD

**Issue by 0x002500** [minecraft-rs/bootstrap#3]
Can you publish it to the crates.io? I want to use it in my new project,please.

**Comment by 0x002500** [comment]
Can you publish it to the crates.io?  I want to use it in my new project,please.

**Comment by sammwyy** [comment]
![image](https://github.com/minecraft-rs/bootstrap/assets/44925968/0c52aa4b-043e-404a-9410-cd9f07ae05c7)

✔

**Comment by 0x002500** [comment]
think you very much
